/* Generated By:JavaCC: Do not edit this line. TableStorageParserConstants.java */
package org.apache.hadoop.zebra.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TableStorageParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMPRESSOR = 7;
  /** RegularExpression Id. */
  int SERIALIZER = 8;
  /** RegularExpression Id. */
  int COMPRESS = 9;
  /** RegularExpression Id. */
  int SERIALIZE = 10;
  /** RegularExpression Id. */
  int ASC = 11;
  /** RegularExpression Id. */
  int DESC = 12;
  /** RegularExpression Id. */
  int SECURE = 13;
  /** RegularExpression Id. */
  int USER = 14;
  /** RegularExpression Id. */
  int GROUP = 15;
  /** RegularExpression Id. */
  int PERM = 16;
  /** RegularExpression Id. */
  int AS = 17;
  /** RegularExpression Id. */
  int LETTER = 18;
  /** RegularExpression Id. */
  int DIGIT = 19;
  /** RegularExpression Id. */
  int OCTAL = 20;
  /** RegularExpression Id. */
  int SPECIALCHAR = 21;
  /** RegularExpression Id. */
  int FSSPECIALCHAR = 22;
  /** RegularExpression Id. */
  int SCOPEOP = 23;
  /** RegularExpression Id. */
  int IDENTIFIER = 24;
  /** RegularExpression Id. */
  int MAPKEYIDENTIFIER = 25;
  /** RegularExpression Id. */
  int SHORT = 26;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "<COMPRESSOR>",
    "<SERIALIZER>",
    "\"compress by\"",
    "\"serialize by\"",
    "\"ASC\"",
    "\"DESC\"",
    "\"secure by\"",
    "\"uid\"",
    "\"gid\"",
    "\"perm\"",
    "\"as\"",
    "<LETTER>",
    "<DIGIT>",
    "<OCTAL>",
    "<SPECIALCHAR>",
    "<FSSPECIALCHAR>",
    "\"::\"",
    "<IDENTIFIER>",
    "<MAPKEYIDENTIFIER>",
    "<SHORT>",
    "\";\"",
    "\"[\"",
    "\"]\"",
    "\":\"",
    "\"#\"",
    "\".\"",
    "\",\"",
    "\"{\"",
    "\"}\"",
    "\"|\"",
  };

}
