/* Generated By:JavaCC: Do not edit this line. TableSchemaParserConstants.java */
package org.apache.hadoop.zebra.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TableSchemaParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INT = 7;
  /** RegularExpression Id. */
  int BOOL = 8;
  /** RegularExpression Id. */
  int LONG = 9;
  /** RegularExpression Id. */
  int FLOAT = 10;
  /** RegularExpression Id. */
  int DOUBLE = 11;
  /** RegularExpression Id. */
  int DATETIME = 12;
  /** RegularExpression Id. */
  int STRING = 13;
  /** RegularExpression Id. */
  int BYTES = 14;
  /** RegularExpression Id. */
  int COLLECTION = 15;
  /** RegularExpression Id. */
  int RECORD = 16;
  /** RegularExpression Id. */
  int MAP = 17;
  /** RegularExpression Id. */
  int LETTER = 18;
  /** RegularExpression Id. */
  int DIGIT = 19;
  /** RegularExpression Id. */
  int SPECIALCHAR = 20;
  /** RegularExpression Id. */
  int SCOPEOP = 21;
  /** RegularExpression Id. */
  int IDENTIFIER = 22;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"int\"",
    "\"boolean\"",
    "\"long\"",
    "\"float\"",
    "\"double\"",
    "\"datetime\"",
    "\"string\"",
    "\"bytes\"",
    "\"collection\"",
    "\"record\"",
    "\"map\"",
    "<LETTER>",
    "<DIGIT>",
    "<SPECIALCHAR>",
    "\"::\"",
    "<IDENTIFIER>",
    "\":\"",
    "\"(\"",
    "\")\"",
    "\",\"",
  };

}
